### ISSUE TITLE
How to send all options attributes

### ISSUE THREAD

**Issue by maxi032** [selectize/selectize.js#1041]
My option item looks something like {"id":8,"text":"France","continent":"Europe","type":"Country"}
when I submit I get only the value of the id. 
How can I retrieve the full item?

**Comment by tlkelley** [comment]
By default, Select controls (as I'm sure you know) send their values when part of a form. The value of an option should be a unique identifier. Standard practice would be to use that unique ID (once server-side) to look up any other information that you may need instead of trying to pass it from the UI.

If, for some reason, you actually _need_ to pass the entire data object, I don't think that selectizejs supports that functionality.

**Comment by joallard** [comment]
Is this related with #1085?

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
