### ISSUE TITLE
Override plugin render

### ISSUE THREAD

**Issue by spib** [selectize/selectize.js#107]
Hi,

I'm using the remove_button plugin, but I'd like to modify the way the text is rendered for selected items (in this case trimming some whitespace). However, it seems that once I include the remove_button plugin, my custom render callback is no longer called.

``` javascript
        $('select[name="category"]').selectize({
            create: false,
            plugins: ['remove_button'],
            render: {
                item: function(item, escape) {
                    item.text = item.text.trim();
                    return '<div class="item">' + item.text + ' <a href="javascript:void(0)" class="remove" tabindex="-1" title="Remove">&times;</a></div>';
                }
            }
        });
```

Is there a way to do this?

Thanks

**Comment by shanthi555k** [comment]
Hi, 'remove_button' plugin for single selectize is working great. but im unable to figure out how to remove that when i use backspace for clearing the selected item instead of remove button.

Either the backspace event should be removed when remove_button plugin is used or it should clear the buttons. Both cases are not working. Please Help!!
