### ISSUE TITLE
Support pagination in remote data

### ISSUE THREAD

**Issue by temuri416** [selectize/selectize.js#1110]
Hello,

It would be great if selectize supported pagination when fetching remote data with AJAX.

[select2](http://select2.github.io/examples.html#data-ajax) has an example of it.

Thanks!

**Comment by lgellert** [comment]
+1

**Comment by joallard** [comment]
@lgellert –1

**Comment by temuri416** [comment]
@joallard meaning...?

**Comment by lgellert** [comment]
To be clear, +1 means "I want this feature also!"  I figured it would be good to provide a sense that others want this feature too.  To elaborate, ajax pagination support in selectize is preventing me switching away from select2.

**Comment by joallard** [comment]
@lgellert Sorry for the reaction, it's just that going through Selectize notifications can take me hours and all those "bumps" do is to take more of my time away from actually improving selectize, all while not changing the aggregate support value that is the number of +1's on the original post. That's why I strongly dislike comments like this that provide no other value. If you want to signal support to this feature, Github has added a +1 system that allows us to sort the issues by votes.

**Comment by lgellert** [comment]
Thanks @joallard, I'll go with thumbs up in the future.

**Comment by joallard** [comment]
Thanks, sorry again. Meanwhile, what would really help getting this done would be doing some steps towards a PR, ie. at this stage, definition, spec'ing and exploring how that might fit in the code.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
