### ISSUE TITLE
Possibility to save value without creating a new option?

### ISSUE THREAD

**Issue by swey** [selectize/selectize.js#1115]
Hi all,

I used selectize before as select replacement, but now I want to create an input with an **autocomplete dropdown** (like the Google Search).

It nearly works with those options set to `true`:

``` javascript
create: true,
createOnBlur: true,
```

But I don't want to create new items in the dropdown list, I just want to enable a free text-input. Any possibility to realize that?
#### Bug with addPrecedence

Also I have a problem with `addPrecedence: false`:
When this is set to `false`, the dropdown is not closed, when no option is present anymore.

The code logic seems to ignore `addPrecedence`: 

``` javascript

has_create_option = self.canCreate(query);
[...]
self.hasOptions = results.items.length > 0 || has_create_option;
```

**Comment by joallard** [comment]
Your issue is not able to be processed as is. Looks like there are two things in here, a question (please use Stackoverflow for questions), and an issue without Steps to reproduce, that looks a lot like #452 (the guide says to search).  Please follow the placeholder text or Guide to reporting issues in the wiki.

**Comment by hotcakedev628** [comment]
@swey 
I have the same issue.
How did you figure this out?
I want to submit the typed value without adding a new item to selectize element.
