### ISSUE TITLE
The option allowEmptyOption doesn't allow to type text in the select box

### ISSUE THREAD

**Issue by DanieleLeo** [selectize/selectize.js#1172]
Hello,

I have noticed that the option "allowEmptyOption: true" disables the possibility to type in the text area of the select box.
I have look for an open issue reporting the same problem, but I haven't find it (so I open this one). 

It's easy to reproduce. You can do this with the fiddle of issue #1165
https://jsfiddle.net/sturchyn/z8wt3zdd/

Steps to reproduce:
1. create a select with an empty value and an empty text
2. set the "allowEmptyOption" to true
3. try to type in the select box

Expected result: we should be able to type in the select box

Actual result: it's impossible to type in the select box

Best Regards
Daniele

**Comment by joallard** [comment]
Thanks Daniele. That's weird indeed!

New str:
1. On fiddle, click on first select to focus
2. Type 'a'

=> Expected/actual

**Comment by markuspl** [comment]
Hi, instead of create a new issue, i will extend this bugreport.

The initial text, which should be displayed as placeholder in selectize will shown as normal text if you use allowEmptyOtions = true.

STR:
- Open Fiddle: https://jsfiddle.net/2usgh4t8/1/ 
- Try to tipe something in the 3rd, doesen't work.
- Change allowEmptyOtions to false
- re-Run the fiddle
- Typing in the 3rd select worked and the text disappears as expected

**Comment by stefan-reich** [comment]
This bug should really be fixed

**Comment by sorcerb** [comment]
I think it should be open again
