### ISSUE TITLE
Auto-Select on click outside

### ISSUE THREAD

**Issue by DannyZB** [selectize/selectize.js#1198]
When the user types in the exact option he wants and clicks outside selectize it loses what he typed.
It should auto select the only relevant option if the user clicks outside and there is one option left.

This is the most natural way to handle that.

**Comment by maral** [comment]
:+1:

**Comment by maral** [comment]
Actually, you can set the option **createOnBlur** to true, which will then create the current specified option when you lose focus, which is what I wanted in case when adding options is allowed. Not sure about selecting the closest option, I guess you can do that with the function **onBlur**.

**Comment by isneezy** [comment]
I'm stuck with this, is there any solution for this??

**Comment by roooodcastro** [comment]
I found [this solution](https://github.com/selectize/selectize.js/issues/999#issuecomment-215785965) from @eklingen88 which paves the way to what you want.

His solution is a plugin that wraps around the original implementation of `onBlur` to "save" the current typed search and reapply it once the infamous `deactivate` function is called inside `onBlur`.

I modified his solution a little and got to [this modified plugin](https://gist.github.com/roooodcastro/0f596666bb85222940519726dadda068).

My solution adds to his in the way that when there's only a single search result, it'll automatically select it when the user clicks outside the input, as he/she probably expects. If there are no results or more than one, the behaviour is the same as defined by eklingen88, just keep the typed text on the input and don't change anything.

I also had to add a hackish if to check if the search result was already set as the selected item, because the `addItem` method was invoking some trigger that I couldn't find that was recursively calling `onBlur` again, resulting in a stack overflow error. There is probably a better way to deal with this, but I don't have the time to look for it right now.

PS: I provided the Gist with the original plugin author's name and license because I couldn't be bothered to change it. Please notify me if this is an issue.

**Comment by RashidShamsi** [comment]
@roooodcastro  with [this plugin](https://github.com/selectize/selectize.js/issues/999#issuecomment-215785965), it keeps the value in input field but not submitting it to the server.
