### ISSUE TITLE
Create a mandatory field

### ISSUE THREAD

**Issue by jahrralf** [selectize/selectize.js#1235]
Hi,

I am trying to use selectize for the different selects in my form. However, I am now stuck with something quite simple: I have a select field in my code where a value must be selected. In HTML, this is just the first option, which is then selected by default.

With selectize it is possible to hit the backspace key to delete the selected value. Is there any way to prevent this?

I have also seen this example here with a "required" field. But still I can press backspace and then the form field is left empty: https://github.com/selectize/selectize.js/blob/master/examples/required.html

Update: I tried this crazy plugin https://github.com/joeholdcroft/selectize-no-delete/blob/master/src/selectize-no-delete.js and it seems to work. But there is one major point: You cannot use the keyboard any more to select a new value by typing in letters! Only up/down work. My idea would be to have the ability to delete value but if you leave the field and no value is selected, then the last value which the field had is applied. I this possible?

Thanks and best regards,

Ralf

**Comment by alzinoviev** [comment]
Seems to be covered by the https://github.com/selectize/selectize.js/pull/838

**Comment by jahrralf** [comment]
Well, only partly. Can it really be so complex to have a mandatory field? For my project, I cannot use the plugin because of the issue.

**Comment by WadeTheFade** [comment]
Here is how I solved it.... its _slightly_ hacky, but its working with no modification of the code base.

First, in your data, make sure you add something as a flag to check for onInitialization:
`[{"UserId":"1","Name":"Wade","ReadOnly":true}, {"UserId":"2","Name":"Bob", "ReadOnly":false}]`

Our goal here is that if the data is marked ReadOnly it will be selected and unremovable/undeletable/unable to be removed.

So on Initialization of multiSelect({}), we will automatically select the ReadOnly option:
```
var userSelectized = $("...").selectize(
        { ...,
            render: {
             item: function (item, escape) {
                return '<div data-readonly=' + escape(item.ReadOnly) +'>' +
                    (item.Name ? '<span class="name" >' + escape(item.Name) + '</span>' : '') +
                   '</div>';
             }
            },
            onInitialize: function () {
                var selectize = this;
                var opts = selectize.options;
                var readonlyVal;
                for (k in opts) {
                    if (selectize.options[k]["ReadOnly"] === true) {
                        readonlyVal = selectize.options[k]["UserId"];
                    }
                }
                selectize.setValue(readonlyVal);
            }
        });
```

However, this still is able to be deleted. Well this is where it gets a little weird.

Lets capture the removal of it.. and add it back:
```
    userSelectize[0].selectize.on("item_remove", function(value, item) {
            if (item.data("readonly")) {
                this.addItem(value);
            }
    });
```

To the user it just seems like they can't backspace to delete it.

If you need more than one default, its just a slight modification to the logic on setting the initial values onInitialize. Hint: pass an array to setValue() instead of a single value.

 ¯\\_(ツ)_/¯

EDIT: Added the missing step of making sure you bubble up your data to the rendered item so it can be read.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by dinhbang** [comment]
Hell @all

How can we add mandatory field without blank selected? sample I have select box below:
`<select id="sex" name="sex">`
`<option value="">Pick a sex...</option>`
`<option value="male">Male</option>`
`<option value="female">Female</option>`
`</select>`
When I delete in search input to blank, next I use tab keyboard then It is elect blank "Pick a sex...". How can disabled select blank value option?

Best regards,
Bang T.
