### ISSUE TITLE
Add support for "single" mode to "delete_button" plugin

### ISSUE THREAD

**Issue by brianreavis** [selectize/selectize.js#124]
Place an "x" to the left of the dropdown arrow for better usability.

Related: #123, #113

**Comment by jacek213** [comment]
+1

**Comment by stefanmeschke** [comment]
+1

**Comment by tonimoeckel** [comment]
+1

**Comment by namkazt** [comment]
still not happen in 2018 👯‍♂️

**Comment by Pictor13** [comment]
Would #1311 make you happy?

I chose to keep the 'x' close to the items, since atm there is a bug that allows to load multiple values even when the `mode = 'single'`.
You can see that bug trying to use `awsome,neat` as input value, in the [_single-select_ example I added to the plugin page](https://github.com/selectize/selectize.js/blob/a7db68ecafa631f6ac211f977e415c5f6f580930/examples/plugins.html#L36).
In that case there would be overlapping multiple crosses, if positioned close to the dropdown-arrow; hence the crosses close to the items.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
