### ISSUE TITLE
Allow duplicate options in load (ajax request)

### ISSUE THREAD

**Issue by sairam2188** [selectize/selectize.js#1274]
Welcome to the Selectize bug tracker. Thank you for taking the time to
make Selectize a better library!

Please keep in mind this repository has an important issue backlog and
that maintainers have limited time to fix issues, triage, and understand
them.

If you've never done so, please read the
[guide to reporting issues](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide)
in the Wiki to help us better understand your issue.

Place an `x` in the checklist steps (`[ ]` becomes `[x]`) to demonstrate
you have done/verified all the steps you needed to do.

Thank you for reading this! You can now erase everything up to the
following dashes, and then complete what's after.

ISSUES THAT EITHER:

* IGNORE THE ISSUE GUIDELINES
* ERASE THE FOLLOWING TEMPLATE
* DON'T FOLLOW THE PROPER NUMBERED FORMAT FOR STEPS TO REPRODUCE

COULD BE CLOSED.

---

I did:

* [x] Search for if my issue has already been submitted
* [ ] Make sure I'm reporting something precise that needs to be fixed
* [ ] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [ ] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

[replace me with a short description of issue]

Steps to reproduce:

1.
2.
3.

Expected result:

Actual result:

[you can add explanations here of the context/what you were trying to
do, and if you have findings about what the cause might be]

**Comment by sairam2188** [comment]
Is it possible to have 2 options with the same value after a request with ajax? 
Example: I have two same emails but with different labels.
Name1 <address@example.com>
Name2 <address@example.com>

The result is only the first option.

Thanks.

**Comment by MatFluor** [comment]
I have the same issue. 

See the JSFiddle to see the effect. Search e.g. for "Total Recall" - there are two Versions of this movie in existence with the exact same Title, one from 1990 and one from 2012 (and another one without date). Hence only one of these will be displayed.

In the Network-tab in Chrome Devtools you see the possible Results (3).
![Results from the Network Tab](https://cloud.githubusercontent.com/assets/2314647/24927274/c9bd8a9c-1efe-11e7-924e-88abb09746a2.JPG)

The correct behavior is seen when the "id" is put into the `valueField` instead of the title.

JS-Fiddle with wrong behavior (title in valueField)
[https://jsfiddle.net/1ahf7dvk/1/](https://jsfiddle.net/1ahf7dvk/1/)

![totrec_wrong](https://cloud.githubusercontent.com/assets/2314647/24927415/3a340e0e-1eff-11e7-94b2-c8a2b6297c7f.JPG)


JSFiddle with correct behavior (id in valueField)
[https://jsfiddle.net/dqoyujh9/](https://jsfiddle.net/dqoyujh9/)

![totrec_right](https://cloud.githubusercontent.com/assets/2314647/24927419/3dd0e44c-1eff-11e7-9af3-90ce66466fe5.JPG)


Disclaimer: The API-key in the fiddle is not mine.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
