### ISSUE TITLE
no way to get selected option index

### ISSUE THREAD

**Issue by mentinghfreightcenter** [selectize/selectize.js#1280]
The index of the currently selected option is a very important & standard feature for the select element in vanilla javascript & HTML. Because selectize removes all options from the existing select DOM element, there is absolutely no way in knowing the index of the currently selected option.

It would be acceptable to use a jQuery selector such as `$('.selectize-dropdown-content .option.selected').index()`,
but the list of drop down items aren't generated in the DOM until the user manually clicks the select box.

**Comment by mmplisskin** [comment]
You could add data attributes to the options to tell you the index.

**Comment by jmichaelterenin** [comment]
I'm sorry, but isn't there an open issue with the original data attributes being removed by the plugin? I'm seeing this as a problem right now, as I try to work with it.

**Comment by kongdd** [comment]
Any solution?

**Comment by shelagh-lewins-ucl** [comment]
Don't look for the generated select element, because there may be more than one on the page and the id is automatically generated.

I found that the selectize object's options have a property '$order' - note that it starts at 1 not 0. And you can get the selected value as the 'items' property of the selectize.

You can use Object.keys(options) to loop through the options, and when you find the option which has the selected value, check its $order.

This code may need to be changed depending on your data structure, but hopefully it gives the idea.

```
const mySelectize = $('.my-selector').selectize;

const { items, options } = mySelectize;

const value = items[0];

const keys = Object.keys(options);

for (let i = 0; i < keys.length; i += 1) {
	console.log('i', i);
	console.log('option', options[keys[i]]);
	if (options[keys[i]].value === value) {
		console.log('selected is item number', options[keys[i]].$order);
		break;
	}
}
```
