### ISSUE TITLE
the drop-down  list  button

### ISSUE THREAD

**Issue by shsh12345** [selectize/selectize.js#1289]
in    the   v0.12.3    and     v0.12.4
1、In the   examples
2、cities.html
3、Click the drop-down list button,choose  one   option，
 then Click the drop-down list button ，
Do not select anything，
then   you   can   not  close   the   drop-down list

please    solve   the   problem     qulickly，I guess it's because the boolean value is not handled properly。
When you solve the problem, please avoid the following problems，

In  your  v0.12.2，no   the    problem，but   in   the    v0.12.2,      the    problem   is    when    you  Switch the window， the   drop-down list   is   open，，，it  is   amazing    me，，，

**Comment by nholden** [comment]
I've noticed this same issue, so I wanted to expand on it a bit here. This is an issue that only occurs when `maxItems` is `1` (and so [`mode` is `"single"`](https://github.com/selectize/selectize.js/blob/32ee80a8ac488ac8ccda3da0252fcce86485bb0f/src/selectize.js#L74)).

Demo: https://jsfiddle.net/d9L79mf4/

STR:
1. Open demo.
2. Click selectize input to open dropdown.
3. Click arrow to close dropdown. Dropdown will flash closed when `onMouseDown` event fires and reopen when the `click` event fires.

![dropdown1](https://user-images.githubusercontent.com/7942714/27771920-85c5e2a4-5f0d-11e7-858f-a54c896012dc.gif)

This only occurs when there is an item selected. If you open the demo and remove the selected item, you'll be able to close the dropdown.

![dropdown2](https://user-images.githubusercontent.com/7942714/27771927-b9675caa-5f0d-11e7-9178-a73a40d98dbd.gif)

I think this is happening because the `close` function (triggered by `onMouseDown`) [intentionally removes focus](https://github.com/selectize/selectize.js/blob/32ee80a8ac488ac8ccda3da0252fcce86485bb0f/src/selectize.js#L1773-L1778) from this specific type of input (when `maxItems` is `1` and there's an item selected) to close the iOS keyboard, but then `onClick` [adds focus back](https://github.com/selectize/selectize.js/blob/32ee80a8ac488ac8ccda3da0252fcce86485bb0f/src/selectize.js#L365-L368) when the user releases the mouse button.

In my project, I wrapped the piece of `onClick` that adds focus back with a conditional so that it doesn't fire in this specific scenario:

```diff
		onClick: function(e) {
			var self = this;
	
 			// necessary for mobile webkit devices (manual focus triggering
 			// is ignored unless invoked within a click event)
 			if (!self.isFocused) {
-				self.focus();
-				e.preventDefault();
+				// This conditional was added for this project and is not in
+				// the Selectize source. In the close function, if
+				// (self.settings.mode === 'single' && self.items.length)
+				// is true, focus is intentionally removed to close the iOS
+				// keyboard. This prevents focus from being readded, which
+				// would reopen the dropdown menu.
+				if (!(self.settings.mode === 'single' && self.items.length)) {
+					self.focus();
+					e.preventDefault();
+				}
 			}
 		},
```

I haven't done any cross-browser testing on this change, and I'm not certain if it will break anything for mobile webkit devices, but it addressed the issue in my specific case.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
