### ISSUE TITLE
Option to supress copying the classes from the target input over to the .selectize-control parent element?

### ISSUE THREAD

**Issue by oller** [selectize/selectize.js#1295]
Hi there, I'm having a little issue integrating selectize dynamically into an app which uses a lot of tachyon's style classes, so a class for border, a class for padding etc.

Any formatting classes applied initially to the `<input/>` element are copied over to the parent `<div class="selectize-control"...>` element.  This leads to double borders and padding as it's nested.

So for example
```html
<input type="text" name="example" class"blah"/>
```
would become
```html
<div class="selectize-control blah">
  <div class="selectize-input items">.....</div>
</div>
```

I can't find in the docs an option to suppressing this copying over of classes, I see there's one similar for the dropdown element `copyClassesToDropdown` which I'm using already.

Does one exist? or should I be implementing this in a different way to avoid this issue, my current fix is a rather clunky toggling of these classes additionally.

Thanks!

I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title

**Comment by magnosis** [comment]
There's the [copyClassesToDropdown](https://github.com/selectize/selectize.js/blob/master/docs/usage.md#data_searching) option for that:

`$("select").selectize({
  copyClassesToDropdown: false
});`

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by bernie-a-smith** [comment]
Hi there,
in my opinion, the issue isn't closed as this obviously hasn't been resolved. I have exactly the same problem. The original poster clearly says that the problem is not with the dropdown, but with the wrapper (selectize-control).
So, are we implementing this plugin incorrectly or is there an option to disable copying classes from the input field to the selectize-control wrapper? If not, can something be added to the options? This would be of great help.
