### ISSUE TITLE
Remove "required" attribute

### ISSUE THREAD

**Issue by gianvito** [selectize/selectize.js#1305]
Hi all,
is there a way to remove the "required" attribute from a selectized select programmatically?

I already tried with:
`$('#mySelect').removeAttr('required')`
`$('#mySelect').prop('required', false)`

but it stays required. I did not find a way through the selectize APIs.
I already tried to call selectize() again on the select, but without any result.

Any idea?

Thank you.

**Comment by AguinaldoAranda** [comment]
I destroy and rebuild the object again to solve this, but I think this technique is bad .., because in my case, I need to set the previous value of select and I only can if I use setTimeout, because if I then set the object reconstruction, the selectize does not identify the set value ...... sadness ...

**Comment by yaseen-ahmed** [comment]
I facing the same issue
