### ISSUE TITLE
Disable sorting

### ISSUE THREAD

**Issue by michalstol** [selectize/selectize.js#1335]
I get from PHP select with options. I dont need sorting this options but selectize it forces me. Why can't we disable this option like {sort: false}?

**Comment by Pictor13** [comment]
I actually tried locally to run the *basic.html* page, from ```examples``` directory, and changed the options of the *Beast:* example.
I removed the *Selectize* setting ```sortField: { field: 'text', direction: 'asc' }``` and the options stayed in the same order as defined in the html.
I also tried to add *multiple* to the select, and change the order of the options in the markup; and still the sorting is retained correctly and not changed.

Are the options in the markup in the order you expect?
Are you maybe loading the options from some ajax request?
Maybe incurring in some sorting made by the *Sifter* scoring function?

**Comment by david-dcp** [comment]
People have been complaining about this lack of functionality since 2014 haha.

There is a hack - Essentially you can retrieve the options from the selectize instance and replace the `$order` values with the order you want. The problem for some(like myself) is that if you have 200+ entries in your dropdown and multiple dropdowns - well not much of a great UI experience when you're waiting for dropdowns to load. :/

The options are indeed resorted - the moment you query for a subset of options. 

We're initialising our selectize instances with no settings - i.e all defaults and those options do change.

@Pictor13  could you please use something like jsFiddle to show us how your results have preserved their order maybe?

**Comment by h0lg** [comment]
I didn't find a way to disable sorting but succeeded in overriding it to do respect a pre-determined order of options. I've outlined it here https://github.com/selectize/selectize.js/issues/1438#issuecomment-555103529

HTH
