### ISSUE TITLE
Provide as packagist package

### ISSUE THREAD

**Issue by JPustkuchen** [selectize/selectize.js#1378]
It would be very helpful to have a maintainer copy of this package available on https://packagist.org/ to use with composer like with npm. Currently there are only third-party packages you should not trust.

Thank you for this great project.

**Comment by sun** [comment]
The integration for Drupal also requires manual installation steps due to the lack of a composer package: https://www.drupal.org/project/selectize/issues/2949060

However, there is https://asset-packagist.org

Selectize is available there as `bower-asset/selectize`: https://asset-packagist.org/package/bower-asset/selectize referencing the Bower package.

**Comment by rodrigoaguilera** [comment]
I think the easiest path forward is to submit a PR with the suggested composer.json and steps on how to submit a package to packagist.org.

This way we avoid to instruct PHP/Drupal folks to add a new repo (asset-packagist) to their root composer.json for the project since packagist.org is the default repo.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
