### ISSUE TITLE
CSS changes from 0.12.4 to 0.12.6 that seriously breaks designs

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#1433]
0.12.4:

```
.selectize-dropdown [data-selectable],
.selectize-dropdown .optgroup-header {
  padding: 3px 12px;
}
```

0.12.6:

```
.selectize-dropdown [data-selectable] {
  cursor: pointer;
  overflow: hidden;
}
```

the padding from version 0.12.4 is not being applied with version 0.12.6, which results in something like this

![Alt Text](http://i64.tinypic.com/1zlc4rr.png)

being displayed like this

![Alt Text](http://i66.tinypic.com/24dr3wp.png)

**Comment by Teemu** [comment]
You need to add class "option".

**Comment by jjinkxy** [comment]
> You need to add class "option".

But this wouldn't apply to the `create` class when you can create your options.

![Screenshot 2019-07-31 at 11 03 36](https://user-images.githubusercontent.com/29758157/62198959-e7f19380-b382-11e9-8d9d-bbc6bf243dbb.png)

The current code only applies to `option` and `optgroup` but since `[data-selectable]` is also added to create-option, `.create` is now missing the padding
https://github.com/selectize/selectize.js/blob/5b06be3d5726c89ed1dbf2ff22eb94b9f2bc60ff/dist/css/selectize.bootstrap3.css#L259-L262

Currently an overwrite can fix the problem:
```
.selectize-dropdown .create {
  padding: 3px 12px;
}
```
![Screenshot 2019-07-31 at 11 10 46](https://user-images.githubusercontent.com/29758157/62199494-deb4f680-b383-11e9-8f34-a845fe3b5ba4.png)
