### ISSUE TITLE
Does readonly is working with input?

### ISSUE THREAD

**Issue by smallersign** [selectize/selectize.js#1452]
I have searched but not clear how it works. 
Its built-in or need customization?

**Comment by ppython** [comment]
If you build your select with html, use the :

> disabled="disabled"

Otherwise you can "disable()" it via the js API.

**Comment by vahidalvandi** [comment]
after disable input send empty array ! why

**Comment by federico-66** [comment]
try this plugin
```
Selectize.define('readOnly', function() {
	var self = this;
	this.setup = (function() {
		var original = self.setup;
		return function() {
			original.apply(this, arguments);
			if (this.$input.is('[readonly]')) {
				this.$control_input.prop('readonly', true);
				this.$control.find('.remove-single').remove();
				this.$control.find('.remove').remove();
				this.disable();
			}
		};
	})();
});
```

**Comment by rodrigoguariento** [comment]
Readonly in selectize is a call to "lock" method. Eg.:

`$('#yourElement')[0].selectize.lock();`

Dynamically is possible to unlock too:

`$('#yourElement')[0].selectize.unlock();`

**Comment by Pictor13** [comment]
> Readonly in selectize is a call to "lock" method. Eg.:
> 
> `$('#yourElement')[0].selectize.lock();`

Yes.
Or something like `$('.selectized:read-only').each(function (input) { input.selectize.lock(); });`, in case we want this to be automatic for any selectized element of the page (beware: do not put this into a widget instantiated multiple times, since it will run the `.each` loop too many times unnecessarily.
Still, would be nice some default way to do it; like the plugin above, just without removing the markup (but just adding a class to hide the `remove-single` and `remove` buttons) and allowing to use a custom `background-color` or style (adding a `.readonly` class to eventually customise in another theme/style).
Also, probably one or two unit-tests should be added to ensure it keeps working.
