### ISSUE TITLE
Mobile phones cannot create new items when there is another selectize field directly after it

### ISSUE THREAD

**Issue by viktorsmari** [selectize/selectize.js#1479]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [ ] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

_I think this is more of a mobile keyboard problem, but maybe there is another way to bypass it._

When using a mobile phone (Android) and trying to add a **new item** by typing in the new name and hitting the (Tab/Enter) key in the bottom right corner on your mobile, nothing happens. This works normally on a computer, either by hitting Tab **or** Enter.

**Steps to reproduce:**

1. On a form where you have **at least** 2 inputs next to each other.
1. On a mobile phone, click the **first** selectize input 
1. Add a new item by typing it in
1. Click the 'Enter' key which might look like this " -->"

**Expected result:**
An item should be added.

**Actual result:**
Nothing happens and the dropdown is closed, and the focus sent to the next input.

If you input a new item "newitem" you get the "Add newitem" option which works when clicked, but if users click the 'Enter' key on their phones keyboard, nothing happens.

If I change the `tabindex` order, and there is nothing **after** the current selectize in the `tabindex` order, I will get the enter key:

**Enter key: (look at the bottom right corner)**
![enter](https://user-images.githubusercontent.com/1689020/54742456-c9ec7900-4bc1-11e9-84a5-4814d12fc7a7.png)

But if I have **another** input form after it I get the 'tab -->' key:

**Tab key?**
![tab](https://user-images.githubusercontent.com/1689020/54742459-cbb63c80-4bc1-11e9-91c0-9d7462250f18.png)

**Comment by Pictor13** [comment]
Mmmh.. pretty curious. Good find!
I don't have an explanation, but I think for the moment you could try adding the `selectOnTab: true` setting when initializing Selectize, so the behaviour should at least be consistent, even with different keys.

For the rest, I am not sure what would cause the button becoming a TAB rather than ENTER.
Are you maybe playing with tabindexes or something?
Is this happening in any of the *examples* pages?

Also, does it happens with different keyboard layouts than Icelandic?

**Comment by Pictor13** [comment]
Also, on https://selectize.github.io/selectize.js/ there are many selectized inputs, one after the other, so it should have the misbehaviour you described.

I tried to access the page via mobile (*Android*, *7.1.1*, *Chrome*, with *Swype* keyboard) and it always showed the ENTER button.
Please report the operative system version, the browser used and keyboard name (you can find this last one, via the "Change keyboard" in the system notifications, when the keyboard is open/shown).

**Comment by viktorsmari** [comment]
I tried the following, but nothing changed:
* Remove all `tabindex`
* Adding `selectOnTab: true`
* Change keyboard layout

I was able to narrow the bug down to the use of `<form>` on Chrome Android

I copied from the examples page to the fiddle:
https://jsfiddle.net/p0ex2jqn/4/

The first 2 inputs **are not** wrapped in a `<form>`.
The 2 last inputs **are** wrapped in a `<form>` - **here** is where it starts to fail.

If you click the **third** input on Android 7.1.2, Chrome, you are not able to add new values with the 'Tab' key.
If you use Firefox + Android, it works correctly!

On an iPhone this works fine, both using Safari and Chrome.

Could this be a Chrome Android bug?

**Comment by Pictor13** [comment]
Hey thanks for the testes, analysis and fiddle.
Yes, you are right; it's a behaviour related to <form> elements, allowing you to tab from field to field, until the last one that will instead allow to submit the filled form data.

I found these two SE threads about the behaviour:
https://android.stackexchange.com/a/32040/80152
https://stackoverflow.com/a/6632329/3088045

Unfortunately that's seems a feature by-design coming from Android. There's unfortunately nothing that can be done to fix it in Selectize (and it probably shouldn't regard it; any hack would mean to wrongly go against the system choices).

This is not a concern of Selectize but just a platform dependant behaviour.
I think the issue should be closed (it will stay indexed for future reference though).

Anyways you can scroll to the other answers in the links, there were some workarounds reported there.
But am not sure if they fit you use case, or if one should even engage with those workarounds, diverging from the system default behaviour (I see not much sense in trying to force a specific behaviour, since it's a _"can't win"_ situation; what if in the future Android will further change this behaviour?).

**Comment by viktorsmari** [comment]
I submitted this as a bug ticket in the Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=957534
