### ISSUE TITLE
Passing values to selectize

### ISSUE THREAD

**Issue by bharathegde45** [selectize/selectize.js#1480]
I want to pass the values from a viewbag that stores a list, to selectize as options. Can I get some help?

**Comment by mota57** [comment]
How can you consider this an issue? you just have to initialize you select element and then initialize selectize. $("myelementSelect").selectize();

**Comment by mota57** [comment]
@bharathegde45 please confirm you did this and close the issue

**Comment by Pictor13** [comment]
Also, take a look at the *examples/* directory:

https://github.com/selectize/selectize.js/blob/master/examples/dynamic.html
https://github.com/selectize/selectize.js/blob/master/examples/movies.html

The first shows how to load a bunch of options, if they are not already present on the original input on which `.selectize()` is applied.
The second shows how to load the options dynamically, performing an AJAX request to a remote URL (your viewbag?).

Also, please:
* next time **use the "Search in repository" function** to find the many issues that have been already opened (and closed) in the past regarding the same concern
* when not knowing how to use a feature, **RTFM** (there's documentation), search the issues, and **ask on StackOverflow.com**. Issues should be used just to report wrong/bugged behaviour, or to discuss implementations or arguments that are _useful for everyone rather than for a specific private project from a single user_.
* take **care of closing the opened issue, after it has been solved**, if there is nothing more to add/write. They are not closed automatically, and it's hard for the maintainers to take care of hundreds issues (since atm there's just a single maintainer with limited time to dedicate to the project).

**Comment by bharathegde45** [comment]
Thank you
