### ISSUE TITLE
[PR Available] Option group header isn't displayed if value is zero (0) or boolean

### ISSUE THREAD

**Issue by winzig** [selectize/selectize.js#1492]
I initiate Selectize using data, not a `<select>` element, and have encountered a bug with option group headers. 

I initialize the Selectize object with this:

```
optgroupField: "Type",
optgroups: [
    {value: 0, label: 'My Label for Zero'},
    {value: 1, label: 'My Label for One'},
    {value: 2, label: 'My Label for Two'},
    {value: 4, label: 'My Label for Four'}
],
```

Notice that "My Label for Zero" has a `value` of `0` (zero). 

Each of my options has a `Type` property equal to 0, 1, 2, or 4. However, the group represented by the `Type=0` never has its header printed in the dropdown. All the other ones appear normally. 

While stepping through the JS debugger where Selectize is working on rendering the option groups, I am seeing a clue. Internally, Selectize is representing the "zero" Type as `""` (empty string), instead of zero:

<img width="769" alt="Screen Shot 2019-06-12 at 10 09 24 AM" src="https://user-images.githubusercontent.com/127062/59371604-59ee1a80-8cfa-11e9-8ce6-60328105ca6a.png">

In that block you can see it's going to fail on the next line down when it reaches this logic:

`if (self.optgroups.hasOwnProperty(optgroup) ...`

Because optgroups has properties of (0, 1, 2, 4), and not `""`, which is what the value of `optgroup` is in this loop. 

I'll update this issue if I can narrow this down further.

**Comment by winzig** [comment]
I'm pretty sure the issue is with this line:

https://github.com/selectize/selectize.js/blob/8c76832f95bae664fb1b533c41df414fc6192ebd/src/selectize.js#L1086

For my data, the value of `option[self.settings.optgroupField]` is 0, and so in that code, is interpreted as false, and thus the optgroup variable gets set to empty string, which is not part of my data.

**Comment by winzig** [comment]
If I change the above referenced line to this:

```
optgroup    = option.hasOwnProperty(self.settings.optgroupField) ? option[self.settings.optgroupField] : '';
```

Then it works as expected. Instead of just checking to see if the value is truthy, it's checking just to see if it exists, and then if so, uses the value as-is. 🎉 

Unfortunately, since I've previously had to fork Selectize to fix other issues that were never merged in, I am unable to create a PR just for this issue. However, it is fixed on [my fork](https://github.com/DiagnosticNetwork/selectize.js) via [this commit](https://github.com/DiagnosticNetwork/selectize.js/commit/17610c37755bfa73bed6cb774daf9ff1af7d7d98).

**Comment by winzig** [comment]
I've found a similar issue if you use boolean values for the optgroups `value` parameter. E.g.:

```
optgroupField: "Type",
optgroups: [
    {value: false, label: 'My Label for False'},
    {value: true, label: 'My Label for True'}
],
```

In this scenario, no headers at all are printed out. I believe this is because  of these two lines that utilize `hash_key`:

https://github.com/selectize/selectize.js/blob/8c76832f95bae664fb1b533c41df414fc6192ebd/src/selectize.js#L1235
https://github.com/selectize/selectize.js/blob/8c76832f95bae664fb1b533c41df414fc6192ebd/src/selectize.js#L1236

There are no comments explaining the reasoning behind this code, so it's hard for me to grasp, but for some reason it's trying to turn the given values from optgroups into strings. E.g. it turns `true` into `1` and `false` into `0`. So later when it's looking up the headers to render, it's looking in my data for `1` and `0`, but those values don't exist, only my original values of `true` and `false`, as one would expect. 

If I delete the second line and change the first to this:

```
var key = data[this.settings.optgroupValueField];
```

Then everything works fine. 

I could see how a change like this could cause problems if the opt group field value is null, so I'm not yet ready to consider this a real fix for this secondary issue.

**Comment by winzig** [comment]
Actually I've found a better way to resolve the secondary issue. Changing this line:

https://github.com/selectize/selectize.js/blob/8c76832f95bae664fb1b533c41df414fc6192ebd/src/selectize.js#L1086

To this:

```
optgroup    = hash_key(option.hasOwnProperty(self.settings.optgroupField) ? option[self.settings.optgroupField] : null);
```

Then everything works, because in both cases my boolean values are being passed through the same `hash_key()` function. (This also fixes an underlying bug where `option[self.settings.optgroupField]` was being evaluated as `false` because of the underlying value, and setting `optgroup` to empty string.)

I've checked this fix into [my fork](https://github.com/DiagnosticNetwork/selectize.js) in [this commit](https://github.com/DiagnosticNetwork/selectize.js/commit/5222379c6089bca8f7a55362ad31c8c908cfb9fb).

**Comment by Pictor13** [comment]
I didn't check accurately but my impression is that the issue is in
https://github.com/selectize/selectize.js/blob/8c76832f95bae664fb1b533c41df414fc6192ebd/src/selectize.js#L1236

`hash_key` is used to ensure that a valid key **must** always be a string; so that function normalizes scalar values that could potentially break code (undefined index, etc). The only notion needed is just that a key is always a string and can either be a valid string key **OR** an empty string.

In the mentioned line `key` is checked to see if it is truthy or empty/false, but forgetting that also `"0"` is a falsy value.
So the issue is actually happening with falsy values (as you said, `false`, `0`, `"0"`, etc).

Although I am not sure if the fix should go in `hash_key`, e.g. choosing `"true"` and `"false"` for converting scalar `1` and `0` number.
Or if the issue is in the reported line, because of shortcutting on the evaluation but forgetting the case of falsy `"0"`.

However, since `hash_key` always returns a string, I would fix it changing that line 1236 to
`if (!key.length) return false;`.

**Please try that and see if it solves your use case.**

Another alternative is to understand that Selectize (and `<select>` or HTML input controls in general) are supposed to work just with strings.
When submitting data there is no concept of *type* of the value; in HTML everything is a string. So strings are what's expected as values and labels.

I suppose that everything works without needing any patch, if you would just provide an array with string values, am I wrong?

````
optgroupField: "Type",
optgroups: [
    {value: '0', label: 'My Label for Zero'},
    {value: '1', label: 'My Label for One'},
    {value: '2', label: 'My Label for Two'},
    {value: '4', label: 'My Label for Four'}
]
```

**Comment by winzig** [comment]
@Pictor13 the changes I described above have fixed all my issues, do you see a problem with the changes made?

I don't think `if (!key.length) return false;` would work because sometimes the key comes back as empty string, which would have a length of zero, which is falsy.

**Comment by winzig** [comment]
In terms of your last question, I did try using strings ("0" instead of 0) and that didn't help.

**Comment by Pictor13** [comment]
> @Pictor13 the changes I described above have fixed all my issues, do you see a problem with the changes made?

Not 100% sure.
Using `null` as a fallback feels inexact, but is not wrong (I think `hasOwnProperty` will cast it to string automatically and will check for a property named `"null"`).
I think in the case the optgroup is `false` then `hash_key` will change it to string `"0"`
(generally speaking it is a mistake to pass the boolean `false` rather than string `"false"`, if that's the label we want; but in that specific case `hash_key` would wrongly change the string value to `"0"`, so this's the value that will be matched with options; options under group `false` will not be assigned a group).

I made some attemts and I found out that optgroups won't be shown when:
- when using non-string values like `false` and `0`; they get converted by `hash_key()` to the same string value, so the last in the loop wins and becomes the optgroup `"0"`.
- when no option has that specific optgroup, then it won't be shown at all (while I believe a classic `<select>` still shows it)

I suppose one solution could be just removing the string fallback value, and the value will always be passed and used as-is.
Not sure, but try simply `optgroup    = option[self.settings.optgroupField];` at line 1079.

> I don't think `if (!key.length) return false;` would work because sometimes the key comes back as empty string, which would have a length of zero, which is falsy.

Right, empty string seems to be a legit value, either as an array key and as <optgroup> label. So theoretically should be an accepted value.

----

Rethinking it, I believe you have just been "lucky" with having the other numeric optgroups be displayed, because of the implicit conversion from number to string (that doesn't work in the case of `0`, where the logical value is preferred and not casted to an usable value).
You shouldn't use integers there. All the examples provided from the repository exclusively use strings as optgroup values.

I'm not sure there is anything to fix here. I know it might be misleading after all that and bug prone when misused, but I think the correct solution is just to **ensure that you use string values for the *optgroups* identifiers**, either in the definition of `optgroups` setting and of `options` setting.

> In terms of your last question, I did try using strings ("0" instead of 0) and that didn't help.

Try changing to string also the optgroups specified in the `options` setting literal.
I tried on the example page and it works.

<img width="470" alt="Screenshot 2019-06-13 at 21 06 03" src="https://user-images.githubusercontent.com/6748874/59460322-1b05b500-8e1f-11e9-9cee-4ae29d78c7b2.png">

**Comment by winzig** [comment]
> I'm not sure there is anything to fix here. I know it might be misleading after all that and bug prone when misused, but I think the correct solution is just to ensure that you use string values for the optgroups identifiers

But that's not what my data looks like. If given the choice between refactoring all my data to fit Selectize, or just fixing the two bugs like I did above, it seems like fixing the bugs is ideal. With the two small changes I made, all values seem to be working fine, whether they be "0", 0, true, false, and so on.

**Comment by Pictor13** [comment]
There's nothing bad, it's a normal practice to map the data for adapting to its destination (here is just about casting one pair to string).

But I'm not saying your patch is not useful.
I just read at your code without trying it so I just can't confirm if the fix won't have other side effects (Selectize is tricky sometimes with edge cases 😬).
Would be great to confirm it, maybe with tests.
But I'm general the changes look fine! Feel free to add a PR :)

**Comment by winzig** [comment]
I wish I could put up a PR, but I've already done PRs from my fork that were never merged in, so not sure how this will impact it. I'll check into it.

**Comment by winzig** [comment]
@Pictor13 I found how to create a PR without messing with my primary fork. The PR is here: https://github.com/selectize/selectize.js/pull/1493
