### ISSUE TITLE
Javascript error

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#1545]
With this code:
```
	<script type="text/javascript" src="/static/infraestructura/selectize.min.js"></script>
	<link rel="stylesheet" type="text/css" href="/static/infraestructura/selectize.default.css" />
	<script>
	('#input-tags').selectize({
	    delimiter: ',',
	    persist: false,
	    create: function(input) {
		return {
		    value: input,
		    text: input
		}
	    }
	});
	</script>

```

I received a strange error (see shot)

![Captura de pantalla_2020-08-20_22-25-05](https://user-images.githubusercontent.com/89915/90822039-1cd8db80-e334-11ea-8088-9ff71e39f218.png)

**Comment by mauricev** [comment]
I may be stupid, but isn't jquery required?

**Comment by rimace** [comment]
@somenxavier Where does it say that? It says only that it is an dependency.
You can use the current version of jQuery.

**Comment by risadams** [comment]
> But you say in [Installation](https://github.com/selectize/selectize.js#installation-and-files) that select.js has jquery.

@somenxavier jquery is a required dependency, but is not included.  The latest version is recommended

**Comment by Pictor13** [comment]
You will get jQuery installed automatically, as peer dependency, if you use NPM version 1 or 2 (see `UPDATE:` note [at the bottom of this explanation](https://nodejs.org/en/blog/npm/peer-dependencies/)).
So no change for really old projects.

When having NPM version 3, then the dependency needs to be explicitly installed, manually, since `peerDependencies` are not handled but they just throw a *`WARN`ing* (that IMHO should really be an *`ERR`or*).

This could probably be made more clear into the README.

**Comment by ghost** [comment]
Thanks.

**Comment by ghost** [comment]
Put in it: https://github.com/selectize/selectize.js/blob/master/docs/usage.md
and mention the version needed.

**Comment by Pictor13** [comment]
I think that `Usage` is more about domain-related details; while in `README` is more environment-related, with details about dependencies, installation, package-managers.

Specifically, this issue is related to NPM's behaviour; the user is supposed to know these version differences already by themselves; it really isn't about Selectize.

But ☝🏻 I think a hint in the `README` already helps a lot, when the user doesn't know NPM; there is also already an example of the installation of a jQuery version; although for specific decisions one should refer to the *semver* in the `package.json`.

IMHO the merge-request from 3 comments ago should be enough.
Of course you can submit a PR if you think that something can be improved; Selectize is maintained just by the community nowadays.
