### ISSUE TITLE
Handle 'input' event.

### ISSUE THREAD

**Issue by marcandre** [selectize/selectize.js#1562]
I did:

* [x] Search for if my issue has already been submitted
* [x] Make sure I'm reporting something precise that needs to be fixed
* [x] Give my issue a descriptive and concise title
* [x] Create a *minimal* working example on JsFiddle or Codepen
	(or gave a link to a demo on the Selectize docs)
* [x] Indicate *precise* steps to reproduce in *numbers* and the result,
	  like below

Reopening #1462

Bug: While not widely known, the input event is triggered before all change events for inputs and selects (see the spec here)

Steps to reproduce:

1. Go to https://codepen.io/marcandre/pen/vQjPxM?editors=1010#0
2. Select any item
3. Notice there is an alert from the standard popup, but no alert from the selectize version

Expected result: It should alert "Hello" from the selectize popup too

Actual result: It doesn't

I'm opening an issue instead of producing a PR because of the huge list of open PRs. As a maintainer I understand how busy one can be, but I also don't want to waste my time. I'll produce a good PR on the promise it will get merged.

**Comment by risadams** [comment]
Hi @marcandre a PR would be welcomed gladly,  we are in the process of getting the project up to speed again which is why older issues are being closed;  If you are willing to create a PR we would ideally like to include tests and if possible performance benchmarks.  This should behave the same way for both single select and multi-select options.

Thanks!

**Comment by marcandre** [comment]
Sure thing #1563
