### ISSUE TITLE
Selectize.js does not allow duplicate options 

### ISSUE THREAD

**Issue by praburaina** [selectize/selectize.js#1592]
Hi guys ,In my application selectize drop-down data only show district values ,how to allow duplicated option.which part I can change in selectize.js

**Comment by risadams** [comment]
What does your data model look like?
In the options you can try setting the `ValueField` and the `SearchField` properties to match the correct items in your model.

There will still need to be something to make the fields unique by value,  otherwise you probably need to re-think what you are presenting to your users and what you expect them to give you back in return.  

Generally speaking, duplicates should be avoided when possible.

**Comment by cuu508** [comment]
An use case I'm considering is a timezone selector with option groups:

![image](https://github.com/user-attachments/assets/3ed7f0d2-b623-42d3-ab3c-f2c5bde58138)

Here, I'm considering using option groups to show user's recently used timezones at the top, and all timezones alphabetically below.

In this example, *I think* I would want `Europe/Riga` to appear in both option groups. Otherwise, if the user immediately scrolls down looking for `Europe/Riga` in the long list, currently they wouldn't be able to find it. Not sure though, I haven't done user testing.
