### ISSUE TITLE
Remote data should stop pending requests

### ISSUE THREAD

**Issue by asped** [selectize/selectize.js#1609]
Hi, 
I am not sure if I can set this up somehow in the options, but I rather think this is a bug (or missing feature?)
When loading remote data with ajax, it can trigger multiple requests, although only the last one is really relevant.

Example:  When the user wants to search for `something`, and he is typing too slow, or the server cannot respond that fast, multiple requests like this are triggered:

`search.json?q[name_contains]=so`
`search.json?q[name_contains]=som`
`search.json?q[name_contains]=somet`
`search.json?q[name_contains]=something`

If the server response takes longer, all the requests are pending, but only the last one is needed.
I think everytime when a new request is created, it should cancel any pending ones.

![image](https://user-images.githubusercontent.com/5485933/112193583-50e8e780-8c08-11eb-90fb-30d3f97e59e7.png)

**Comment by databyte** [comment]
There is a debounce already in the codebase to help handle this.

You'll want to set the `loadThrottle` option. Please [see the documentation](https://github.com/selectize/selectize.js/blob/master/docs/usage.md) for `loadThrottle`.

**Comment by asped** [comment]
thanks for the info, it may help a bit, but in my case (very slow server), it will not fix the issue, as I cannot precisely "predict" how long it will take for the server to respond. So the requests will still stack up.
Maybe would be a good feature for the future then.

**Comment by databyte** [comment]
That's what debouncing does though. If a request hasn't completed but a new one starts, it'll cancel the old one. By not setting any value, it doesn't do it at all.

The documentation states:
> The number of milliseconds to wait before requesting options from the server or null. If null, throttling is disabled. Useful when loading options dynamically while the user types a search / filter expression.

Basically by not setting this, you're allowing the control to send 5 requests which further bombards your server and makes things slower.

I would try setting it to at least something, big or small just something so that the calls don't pile up.

Two other suggestions:

1. You could also require a minimum number of characters for onChange and cancel previous calls onChange.
2. If your server truly is that slow and always will be then don't allow ajax calls at all. Allow users to type a partial query then click "Search" and return the results yourself then populate the field yourself.
