### ISSUE TITLE
clicking on scrollbar in ie10 causes dropdown to close

### ISSUE THREAD

**Issue by ghost** [selectize/selectize.js#182]
In the bottom demo (selecting states) on http://brianreavis.github.io/selectize.js/, clicking on the scrollbar in IE10 will cause the dropdown to close.  I've tested it on IE10 on windows 7 and windows 8.  The click triggers a blur event that somehow needs to be ignored by selectize.  For comparison, select2 doesn't seem to have this issue, but I'm not quite sure how it's avoiding it.  Works fine on Firefox, Chrome and Safari/IOS.

**Comment by mwentz** [comment]
FYI, we ran into this exact issue with 0.12.0 and it turned out to be a javascript conflict. The conflict was with the Google Polymer Project Paper elements, using Bower. I don't think there's any need for this issue to be addressed on the selectize.js side, but I wanted to bring this up in case there is, and also I thought this might be helpful for anybody that finds this ticket and is using 0.10.0+.

**Comment by rohansahai** [comment]
hmm having this issue in 0.12.1 ...

I never make it in here - https://github.com/selectize/selectize.js/blob/master/dist/js/selectize.js#L1064 because `document.activeElement` appears to be the parent element of `self.$dropdown_content[0].classList`. Still digging into to try and figure out what's going on but if anyone has run into this please let me know! @mwentz did your j conflict have this side affect or unrelated?

EDIT - I think this there is conflicting css on my side

**Comment by seb-grant** [comment]
I have the same issue as @rsahai91 - have patched my local copy to check activeElement for the dropdownClass instead.

This solution works for me, but I'm not sure how the equality check (`document.activeElement === self.$dropdown_content[0]`) works for some users and not for others.
