### ISSUE TITLE
Disable sifter functionality ? 

### ISSUE THREAD

**Issue by armandoxxx** [selectize/selectize.js#196]
Hey .. 

Is there a way to disable Sifter search and sort after my data is loaded from server ? 

Data received from server is already sorted and prepared for output so no additional stuff is needed ... 

any help would be appreciated

regards

Armando

**Comment by philipwalton** [comment]
+1

My dataset is already presorted based on popularity, so selectize trying to be smart about matching it is actually counterproductive in this case.

I like how customizable the rest of this plugin is, I'm surprised a no-frills searching option isn't available.

**Comment by philipwalton** [comment]
Seems like this can be done with a pretty involved workaround:
1. Loop through my options array and add an `index` property to each item corresponding to that item's array index.
2. Explicitly set the sort criteria to use my `index` property.
3. Override the score function to either return `1` for _any_ match or `0` for no match.

This means that all results either have a score of `0` (so they're not shown) or `1` and they're shown. Selectize seems to use the sort option when more than one result has the same score.

Here's the code that worked for me:

``` js

/* 1 */
options = options.map(function(option, i) {
  option.index = i;
  return option;
});

$(input).selectize({
  options: options,
  searchField: ['id', 'name'],

  /* 2 */
  sortField: [{field: 'index', direction: 'asc'}], 

  /* 3 */
  score: function(search) {
    var score = this.getScoreFunction(search);
    return function(item) {
      return score(item) ? 1 : 0;
    };
  }
});
```

Anyway, it would be nice if the `score` option could be specified as `"flat"` or something like that to indicate that all matches are treated equally. It would also be nice if you could specify the array order as the default sort order instead of having to manually add an index.

**Comment by cgs** [comment]
thanks for your workaround @philipwalton. Started trying to add a no sort option but got quickly lost in the abyss...

**Comment by broerse** [comment]
This also seems to work:

``` javascript
  sifter = new Sifter(input);
  sifter.getSortFunction = function() {
    return null;
  };
  result = sifter.search(query, options);
```

**Comment by ishirav** [comment]
+1 
leaving filtering and sorting to the server would be a very useful option to support.

**Comment by broerse** [comment]
@ishirav It is supported. But not well documented. See also:

https://github.com/lazybensch/ember-cli-filter-by-query/commit/e0d05a6d681e483f801aff1c3fad7316d216fd68

**Comment by Kallin** [comment]
:+1:

**Comment by PavelGonzales** [comment]
So, guys, could you please give me a clue, how do I disable filtering?

**Comment by broerse** [comment]
https://github.com/lazybensch/ember-cli-filter-by-query/blob/master/addon/util/filter.js#L32

**Comment by PavelGonzales** [comment]
how can I use this with angular?

**Comment by PavelGonzales** [comment]
I found the solution, in the config write:
score: function() { return function() { return 1; }; },

ES6: 
score: () => () => 1,

**Comment by PritishC** [comment]
I think @broerse has it [right](https://github.com/selectize/selectize.js/issues/196#issuecomment-117247838). If I go by this `score` approach instead, I find that on multiple searches, the options list does not clear and the results keep accumulating. It might be because I'm on an older version of selectize - v0.12.3, but just thought I'd share what worked for me.

**Comment by h0lg** [comment]
This seems to be a working solution: https://github.com/selectize/selectize.js/issues/218#issuecomment-153303625

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.

**Comment by itsems** [comment]
Big Thanks to @philipwalton ! You save my day
