### ISSUE TITLE
Plugin Architecture + Custom Builds

### ISSUE THREAD

**Issue by brianreavis** [selectize/selectize.js#20]

**Comment by Pictor13** [comment]
Plugin system is great. One of the best features of the lib 😄👍 

And
> custom features that live in their own repos—which get included as separate scripts

is possible; but I can't manage to have scope access to the *utils.js* functions, inside my custom plugins. Unless I don't compile my own build (that I would like to avoid).
If I define a plugin from outside of the *wrapper.js* (because I keep it in my own repo, and can't add the plugin directly in the *selectize.js/src/plugins* directory) there is no way I can reuse methods like *getSelection* and *escape_html*, or refer to some constants like *TAG_SELECT*.

Is there any way I could get access to them?
