### ISSUE TITLE
`addItem(value)` do not work when using ajax

### ISSUE THREAD

**Issue by salarmehr** [selectize/selectize.js#201]
I want add some items to a selectized input after user clicks on a button. The input data are loaded via Ajax. When I call `addItem(value)` no thing happens. But if I try to type some string in the input it loads data and after this `addItem(value)` will works.

**Comment by nmnandakishore** [comment]
Make sure you add the item after the data loaded through ajax.

``` javascript
    load: function(query, callback) {
            // if (!query.length) return callback();
            var that = this;
            $.ajax({
                url: 'http://localhost/ed/api/receiver.php/' + encodeURIComponent(query),
                type: 'GET',
                error: function() {
                    callback();
                },
                success: function(response) {
                     callback(res);
                     /* write the code to add items here */
                 }
            });
        }
```

**Comment by v2lrf** [comment]
> ```js
> /* write the code to add items here */
> ```

Hi everyone and hi @nmnandakishore this is exactly what I'm not able to do. i have posted an issue [here](https://github.com/selectize/selectize.js/issues/1491) and this is, I think the problem. 
> ```js
>  success: function(response) {
>                      callback(res);
>                      /* write the code to add items here */ 👈🏼
>                  }
> ```
There is no connection inside my code between the Json send and the Render option. That's why I'm only able to display the ``` :name ``` and the ``` :id``` inside the render option all other attribute are considered as undifined..
here the GIF i did and [here](https://github.com/selectize/selectize.js/issues/1491) the issue i have posted . If you have time to share peace of example or a advice on how to build that code . The code that i misunderstood is exactly where you wrote this sentence  /* write the code to add items here */... 
Actually where i am
```javascript
success: function (res) {
	callback(res.data.map(function (item) {
		return {
			 name: item.dashboard_display_name.name,
			 label: item.dashboard_display_name.label,
			 score: item.watchers.score
		 };
	 }));
}

```
But not abble to pass any item to the render ...
![](https://res.cloudinary.com/entrepreneur/image/upload/v1559574091/final_5cf5360ed5a13e0013dd4d19_823434_l3xmnw.gif)
have a beautiful day

**Comment by HHGB12** [comment]
✅ Work Well 
## for Ajax (remote data) , Json , Rails, item dropdown , Selectize Vs Select2 ?

Finally, job done and work fine with Select2 🤷🏽‍♂️


![](https://res.cloudinary.com/entrepreneur/image/upload/v1559645341/final_5cf64c1c785bd00014c11dab_239008_bs75wd.gif) 



if need the access repo tell me bye

**Comment by HHGB12** [comment]
✅ Work Well 
## for Ajax (remote data) , Json , Rails, item dropdown , Selectize Vs Select2 ?

Finally, job done and work fine with Select2 🤷🏽‍♂️


![](https://res.cloudinary.com/entrepreneur/image/upload/v1559651584/final_HW_select2_ajax_JSON_zqtj7v.gif) 



if need the access repo tell me bye
