### ISSUE TITLE
IE Auto-Width Bouncing Scrollbar

### ISSUE THREAD

**Issue by locux** [selectize/selectize.js#215]
I noticed that when we adjust the CSS to allow the width to auto-size to the content in IE10+ the scroll bar (when clicked) will often jog to the left the width of the scrollbar.  Feels glitchy.  Only happens in IE10+.  IE9 will cut-off the right side of the select options.

Here's a fiddle displaying the issue:  http://jsfiddle.net/rdX5R/4/

This was fixed in 0.8.5 with the following diff.  (lines might be very slightly off from 0.8.5 as my source diff has patch already committed from bug #182.  

```
17c17
<

---
>         var widthcount = 0;
1545a1551,1557
>                     if (widthcount == 0) {
>                         self.$dropdown_content.css({
>                             width: self.$dropdown_content.width() + 15
>                         });
>
>                         widthcount = 1;
>                     }

```

Here's a fiddle with this patch: http://jsfiddle.net/rdX5R/5/

p.s. This fix also solved issue #173 for me.

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open and add details following the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide).
