### ISSUE TITLE
Cannot call method 'mixin' of undefined 

### ISSUE THREAD

**Issue by sylouuu** [selectize/selectize.js#219]
Hello,

Got this error on the line: `MicroPlugin.mixin(Selectize);`

Using jQuery 2.0.3. Using selectize 0.8.5.

Calling with:

``` javascript
$('select').selectize();
```

Regards

**Comment by dougfarre** [comment]
how would i tell bower which to use?

**Comment by dlong500** [comment]
As @9mm stated, the minified version of the standalone version also gives this same error.  It would seem there is a build misconfiguration with generating the minified version of the file since the unminified standalone build works fine.  This is still true as of 0.12.1.

**Comment by serchavalos** [comment]
Same here. I had the same issue like @9mm and @dlong500

**Comment by ghost** [comment]
I have the same problem as @9mm 

The minified version gives the same error... "Unable to get property 'mixin' of undefined or null reference"

**Comment by JasonMannon** [comment]
I am unable to use and of the standalone builds.

**Comment by stevoPerisic** [comment]
This is still an issue, the standalone builds are not usable because they are missing the microplugin.js and the sifter.js code. You can find those here https://github.com/brianreavis/microplugin.js/blob/master/src/microplugin.js and here https://github.com/brianreavis/sifter.js/blob/master/sifter.js

Once I added those into the selectize.js it solved the problem. Hope that helps!
