### ISSUE TITLE
Ajax form submission & selectize?

### ISSUE THREAD

**Issue by landwire** [selectize/selectize.js#272]
Hi there,
I am using ajax to submit form values (some are in a selectized <select>). I save the form as a jQuery object before it is submitted, then after submission I append it again at the original position. Ready for new action, but unfortunately the selectized <select> fields are not working then. They show the updated value (set by .defaultValue), but no dropdown appears when I click onto the fields. As is just nothing happens. I can "unhide" the "selectize-dropdown" with FireBug, but nothing is working anymore. Any ideas how I can "re-initialise" those fields? I tried resetting the form with .reset(), but that did not seem to make a change either.

Apart from that I just started using something like selectize.js and it seems so much nicer to work with then the "chosen" one which I tried yesterday! Many many thanks for making this beautiful bit of code!
Sascha

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since the issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open. If you haven't done so, read the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide) and make sure your original post follows the guide.
