### ISSUE TITLE
Preload callback

### ISSUE THREAD

**Issue by heruan** [selectize/selectize.js#281]
I have a search field which need to get pre-populated with values saved in local storage. Then, the first call to the `load` callback should be different from the one called when the user types into the field. It would be nice to have the `preload` option able to take a callback which would be called on initialisation.

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open and add details following the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide).

**Comment by heruan** [comment]
I'm not using selectize anymore, so I can't test the latest version in any of my projects.

**Comment by joallard** [comment]
It looks like an interesting feature. If someone else feels the need, they can reopen. Thanks!
