### ISSUE TITLE
.text() returning blank

### ISSUE THREAD

**Issue by davidbell** [selectize/selectize.js#286]
Hi, I've not had much time to look into Selectize but I found .val() working fine but when I wanted to copy out the option's text .text() was empty. I've made a quick small change I'll just show here, sorry I can't look into it more but this is working fine for me and I've a deadline creeping up.

Line 2468

``` javascript
options.push('<option value="' + escape_html(self.items[i]) + '" selected="selected"></option>');
```

Changed to:

``` javascript
options.push('<option value="' + escape_html(self.items[i]) + '" selected="selected">' + self.getOption(self.items[i]).html() + '</option>');
```

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open and add details following the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide).
