### ISSUE TITLE
dynamic maxitems

### ISSUE THREAD

**Issue by yiorgos78** [selectize/selectize.js#297]
On a multiple select box if i set maxitems=2 it awaits for 2 options to get selected and then closes the dropdown. Can the dropdown close every time an option is selected until maxitems no is reached? Users get confused by the fact that they have to click somewhere else in order to close the dropdown with only one option selected.

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open and add details following the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide).
