### ISSUE TITLE
Allow custom inputs?

### ISSUE THREAD

**Issue by xedi** [selectize/selectize.js#300]
I've had a look though the documentation and can't find a way of allowing custom inputs for dropdowns. Is there a way to do this?

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open and add details following the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide).
