### ISSUE TITLE
update values dynamically with slider

### ISSUE THREAD

**Issue by kprovance** [selectize/selectize.js#312]
I'm using the nouislider (reference: http://refreshless.com/nouislider/example-html5-input) that allows one to use a select box that updates the value with the slider.  The select box initializes fine, but when the slider is moved, the values do not update, as they would with a standard select box.  I get the select box needs to be reinitialized, somehow.  I've tried using the API provided, refreshItems, refreshOptions, even destroying it and attempting to recreate it.  Nothing works.  Is there a clean cut way to reinit the select box with selectize, or am I simply out of luck?

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since this issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open and add details following the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide).

**Comment by kprovance** [comment]
lol, that's coz no one ever answered!!  Doesn't matter.  We ended up going with a different solution.  Thanks anyway.
