### ISSUE TITLE
Sorting not firing

### ISSUE THREAD

**Issue by blaher** [selectize/selectize.js#315]
I'm using Selectize on an application that in the works. And based on filter data, my options are constantly changing based on Ajax returned. I keep running in to instances however, where sort is not catching on correctly. I am using the column "count" in sifter to sort by and also in the template for myself to see easily. I've found that .refreshItems() will fix my issue and resort correctly, however I have an .change() binded to each select. I want to avoid binding and unbinding while I run .refreshItems(). Is there any way for me to fire off something in order to get Selectize to resort without triggering my .change()?

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since the issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open. If you haven't done so, read the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide) and make sure your original post follows the guide.
