### ISSUE TITLE
Cannot type after zoom or scale is changed on IOS7

### ISSUE THREAD

**Issue by sarts3** [selectize/selectize.js#359]
I am trying to use selectize and everything works fine except when I changed the zoom level on my iphone, I am not able to change the text inside the select. It is frozen, unreactive.

I think the problem may be in the css because if I remove everything looks ugly but I am able to type without problems

Any idea? Thanks in advance

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since the issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open. If you haven't done so, read the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide) and make sure your original post follows the guide.
