### ISSUE TITLE
I want to preselect the selectize with some values in case of editing my form which I submitted earlier. How can I achieve this

### ISSUE THREAD

**Issue by ravis2014** [selectize/selectize.js#413]

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since the issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open. If you haven't done so, read the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide) and make sure your original post follows the guide.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
