### ISSUE TITLE
Natural sort order

### ISSUE THREAD

**Issue by mistic100** [selectize/selectize.js#440]
Hello

is there a way or a plan to use natural sort order for the option list ?

my items have a field "global_rank" (used as `sortField`) which can be (ordered):

```
1
1.1
1.2
....
1.10
1.11
```

currently it's sorted as:

```
1
1.1
1.10
1.11
1.2
....
```

I would like to avoid using an external sorting populating an "$order" field

Thanks

**Comment by brianreavis** [comment]
I'm kind of with @hidegh on this one. For your use case, can you just make the `global_rank` field a Number? As for using natural order for strings... that gets really complicated, and has the potential to make the sorting sluggish on large lists / older computers. If you like, open an issue on sifter and we can talk about it there.

Check out: https://github.com/Bill4Time/javascript-natural-sort/blob/master/naturalSort.js

If that were implemented, it'd have to be an opt-in feature. E.g:

`{field: 'title', direction: 'asc', natural: true}`

**Comment by mistic100** [comment]
No I can't change the format of my `global_rank` field.

Although I don't need this feature for now, I still think it's something interesting. I'll see what can be done in sifter (optional of course) and make a PR.

**Comment by hidegh** [comment]
To @mistic100

in an other project we have similar strings to yours.

**there are only 2 solutions**

1 - if you know there won't be more than 10/100 or 1000 items on a single level, then use prefixing, so you'll get 001/002/003 like strings that can be sorted as text and order will be as you expect.

2 - this is what we did (since our client also wanted to have so called unique id from 1..n beginning on the top item in the tree and flowing down across). but this is not an easy way to implement, you need to update all existing ranking-id's when you insert or delete somewhere to/from the middle.

3 - is to implement something you wan't, but this is related to performance problems - for each item you have to split, parse strings to integer, etc... or use re-entrant (recursive) functions, etc. and doing something similar on the client is bad.

also to the idea of yours: what would happen, if you'd decide to use decimal numbers? each client may use other culture, thus parsing your's 1.1 may result in an exception if client is accepting only comma as the decimal value...and we haven't mentioned group separators, neither negative sing formats or currencies...

hope you see why this is something that should not be done on the client, via JS.

**Comment by mistic100** [comment]
And what you seem to not understand is that the natural sort algorithm is GENERIC, check the examples of the library Brian linked. Nobody cares what I use for separator.
