### ISSUE TITLE
Why can not verify multiple select

### ISSUE THREAD

**Issue by xieguihua** [selectize/selectize.js#441]
![image](https://cloud.githubusercontent.com/assets/7709544/3087152/821a43f2-e54e-11e3-93ef-057e8b7c4427.png)

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since the issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open. If you haven't done so, read the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide) and make sure your original post follows the guide.
