### ISSUE TITLE
item click in IE8 fires 2nd time 

### ISSUE THREAD

**Issue by artiaggarwal** [selectize/selectize.js#445]
Select item on click works fine in all browsers except IE8.  first item click works fine. if you click on another item in the same selectize, it deselects the first selected item but does not select the second item. another click in second item selects it.  i need to support IE8 for clients so really need this to work as expected. any suggestions/ fixes welcome.

**Comment by joallard** [comment]
Thanks for reporting this issue. I am closing it since the issue has been inactive for more than 2 years. If there is still a problem with the latest version, please re-open. If you haven't done so, read the [Issue reporting guide](https://github.com/selectize/selectize.js/wiki/Reporting-issues-guide) and make sure your original post follows the guide.
