### ISSUE TITLE
Is there an embedded/inline version

### ISSUE THREAD

**Issue by ragulka** [selectize/selectize.js#482]
I am looking for a component that would work just like Selectize does, except that I want the options to be always visible so that I can embed the component on the page. Something like a datepicker that is not in a dropdown, but on page.

Can I achieve something like this with Selectize or perhaps there are some alternatives that do this out of the box?

**Comment by hagabaka** [comment]
Just wanted to say that @ragulka's fiddle might be initially confusing, because it has a button that toggles display of the dropdown, but it does contain code that keeps the dropdown always open:

```
Selectize.define('component', function() {
    var self = this;

    this.on('initialize', function() {
        self.open();
    });

    this.close = (function() {
        return function() {};
    })();
});
```

Use `component` as a plugin when initializing selectize.

If nothing else, this helps with using inspector on the dropdown entries to see and tweak their styling.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
