### ISSUE TITLE
scroll event changing custom width.

### ISSUE THREAD

**Issue by pgee70** [selectize/selectize.js#493]
Hi
i use a narrow control (postcode) to select a wide dropdown (suburb/state)
I use onDropdownOpen to change the width of my dropdown width using $dropdown.css('width','300px');

when i scroll the positionDropdown takes over and sets the width to $control.outerWidth();

is there a way around this? an optional parameter for dropdown width is my suggestion.

before:
![image](https://cloud.githubusercontent.com/assets/5938974/3419656/b9f85534-fe71-11e3-8dd7-832f9ad5d169.png)
after:
![image](https://cloud.githubusercontent.com/assets/5938974/3419657/c7824a16-fe71-11e3-9014-09554ac72198.png)

**Comment by michaelfeihstel** [comment]
I know this is an old issue, but I just ran into minor problems with the width of the dropdown. For whatever reason, the width of the dropdown doesn't completely line up with the input above when using explicit pixel values from $control.outerWidth(); - try it by zooming in, you'll notice a 1px offset at certain zoom levels.

Instead of setting the width in px in javascript, it might be a good idea to always use
- 100% as opposed to the px value, with percentages the dropdown is always perfectly aligned with the input above it
- leave it in the stylesheet, not the js file
