### ISSUE TITLE
When using create wait for the response of the API to call callback

### ISSUE THREAD

**Issue by jonnywhile** [selectize/selectize.js#591]
When using the create option there is an issue when i am trying to create a new item both in the front end but also send a post request to the API. I need to wait for the callback of the API so i could inject the newly created ID as the value for the option.

**Comment by KendallPark** [comment]
+1 same here.

**Comment by pelargir** [comment]
+1

Supposedly we can use create with a callback to accomplish this, but I find that any time I make an async Ajax call from within the create function, nothing shows up in the selectized field. As soon as I turn off async, everything starts working. But making non-async Ajax calls is discouraged since it locks up the browser for the duration of the call. Selectize doesn't seem to like async Ajax calls embedded within its own functions for some reason.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
