### ISSUE TITLE
Sort assistance

### ISSUE THREAD

**Issue by hotmeteor** [selectize/selectize.js#616]
This is my data:

```
[{
"name":"The Factory",
"address":"5 Hapuku Road",
"locality":"Kaikoura",
"region":"Canterbury",
"country":"NZ",
"postal_code":"7371",
"lat":-42.334078,
"lng":173.722039,
"tel":null,
"url":null,
"id":"2f866e0bbcda8ccd10b4e3531b98b42e",
"country_long":"New Zealand"
}]
```

My settings are:

```
{

        delimiter: false,
        create: false,
        maxItems: 1,
        persist: false,
        openOnFocus: false,
        highlight: false,
        loadThrottle: null,

        valueField: 'id',
        labelField: 'name',
        searchField: ['name', 'address', 'locality', 'region', 'country', 'country_long'],
        sortField: [{
            field: '$score',
            direction: 'desc'
        }],
...
}
```

I'm typing in `the factory hapuku`, which is the `name` and a partial `address` and getting no dropdown results, even though data returns from the server.

Is this a valid search to get results? If so, what is the suggested `searchField` and `sortField` values?

Thanks

**Comment by h0lg** [comment]
Without any surrounding code that e.g. shows how you load the options, I doubt anyone will have enough information to help you. So if after five years you still have not solved this, I suggest you provide more information or even a jsFiddle demoing your problem. Otherwise you might want to close this issue. Cheers
