### ISSUE TITLE
valueField and Create options not playing along

### ISSUE THREAD

**Issue by nine-2-five** [selectize/selectize.js#721]
When valueField option is set (like in case of my ajax load inputs), the create option is not working. When new tag is entered in the field and the field looses focus, the tag is lost.
This is someone else's fiddle but it shows the point:
http://jsfiddle.net/2ZrEu/

**Comment by tjperovich** [comment]
The reason the new tag gets lost is because the new tag lacks the specified `valuefield`. That code specifies `valuefield: "item"` which is missing from the create function:

```
create: function(input) {
    return {
        value: input,
        text: input
    }
}
```

Do you see the field `item` anywhere? I don't. So let's try adding an item field: 

```
create: function(input) {
    return {
        item: input,
        text: input
    }
}
```

And poof it works. This works as well:

```
create: function(input) {
    return {
        value: input,
        text: input,
        item: input
    }
}
```

Selectize is extremely flexible. Just gotta read the docs.

**Comment by PhiLhoSoft** [comment]
@isvaljek should close this issue...
