### ISSUE TITLE
Load more content/infinite scrolling with Ajax

### ISSUE THREAD

**Issue by shoaibshakeel381** [selectize/selectize.js#773]
I have thousands of records in my database and i can't load all of them at once in selectize. Currently I'm using selectize such that i filter results by user input on server side and return all of them. This isn't very good approach because if there are too many results then all of them are fetched from database. I need autoloading of records through ajax when user scrolls through records. Can selectize handle this? If yes then how? What other options do i have for this scenario?

**Comment by Borzik** [comment]
In my opinion searching for desired option in a list of more than 20 options [would be a pain for each user](http://uxmovement.com/forms/stop-misusing-select-menus/). Needless to say, for hundreds or thousands of records it would be much worse UX (and infinite scroll feature will slow that process down even more).
So I'd recommend you having good search algorithm, which will first show most popular items, limited to 10 or 15 (and if user refines a query, fetch options which suit him most). 
Or, if the situation allows you, just split them into a few selects. For example: instead of having one list for all cities in the US, you can add state select, and when user selects his state, show only cities which belong to that (also limited by 15, and sorted by popularity).

**Comment by shoaibshakeel381** [comment]
In my case I have clients records which cannot be broken down into sub groups.

**Comment by igorlino** [comment]
Maybe tthese 2 plugins are related:
https://github.com/diegoleme/selectize.infinitescroll.js
https://github.com/jimmyngo/selectize-infinite_scroll

**Comment by donhuvy** [comment]
How to load more with button **"Load more..."**? I mean that it don't load data automatically.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
