### ISSUE TITLE
Optgroups does not recognise value 0

### ISSUE THREAD

**Issue by Trexology** [selectize/selectize.js#906]
I have Optgroups with value 0, when configuring 

optgroups: [
        {value: '0', label: 'Main'},
        {value: '1', label: 'For People'},
        {value: '2', label: 'Occasion'},
        {value: '3', label: 'Characteristic'}
      ],

value 0 are ignored. tried with 0, '0' and "0". All does not work.

json data returned as int 0

using with laravel 5.1

**Comment by PhiLhoSoft** [comment]
I think the bug is in the `registerOptionGroup` method:

```
    registerOptionGroup: function(data) {
        var key = hash_key(data[this.settings.optgroupValueField]);
        if (!key) return false;

        data.$order = data.$order || ++this.order;
        this.optgroups[key] = data;
        return key;
    },
```

The `if (key`) part is the culprit, as JavaScript will coerce the `'0'` key into `false` in this test (idem if you try to use `'false'` or an empty string...).

The test should be `if (key === null)` since that's what `hash_key` returns on `null` or `undefined` input.
I can see the same issue in the `registerOptions` function, while `updateOptions` and `getElementWithValue` has the more precise version of the test.
`render` and `init_select` might have the issue as well.

Conclusion: until this is fixed, you might want to avoid using such key.
Alternative: you can use monkey patching to fix the faulty method, ie. just replace `registerOptionGroup` with your own version.

**Comment by risadams** [comment]
closing stale issues older than one year.
If this issue was closed in error please message the maintainers.
All issues must include a proper title, description, and examples.
